name: Markdown Link Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run lychee link checker
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: >
            --verbose
            --no-progress
            --exclude-path README.md
            ./docs/**/*.md ./README.md ./CONTRIBUTING.md
